### ISSUE TITLE
A mode without webpack.

### ISSUE THREAD

**Issue by Natim** [mozilla/testpilot-ga#3]
We'd like to be able to use the library without the need to setup webpack.

**manifest.json**

```
  "background": {
    "scripts": [
      "vendor/testpilot-qa.js",
      "background.js"
    ]
  },
```

But when we do that, we have the exports is not defined error.

**Comment by chuckharmston** [comment]
`0.2.0` published [on NPM](https://www.npmjs.com/package/testpilot-ga), which includes this fix.

**Comment by Natim** [comment]
Apparently it has not: https://unpkg.com/testpilot-ga@0.2.0/dist/index.js
